### ISSUE TITLE
Add TargetFrameworks netstandard2.1 or net6.0 for Tingle.AspNetCore.DataProtection.MongoDB

### ISSUE THREAD

**Issue by ThomasTosik** [tinglesoftware/dotnet-extensions#142]
Hi,

would it be possible to add the TargetFrameworks netstandard2.1 or net6.0 to the Tingle.AspNetCore.DataProtection.MongoDB project? The project Tingle.Extensions.Caching.MongoDB for example does support it. And i dont see any obvious code the wouldnt compile. This would help to use this project in a net6 environment.

Regards

Thomas

**Comment by mburumaxwell** [comment]
This sounds like a reasonable request. We shall add net6 to the list

**Comment by ThomasTosik** [comment]
> You can also do a PR that overrides the value in the specific project.
See #144
